---
title: "Gestión de Proyectos en la Ingeniería Civil"
author: "Neila González Tejada"
date: "`r Sys.Date()`"
output: html_document
site: bookdown::bookdown_site
bibliography: ProjectI.bib
csl: apa.csl
---

# Importancia de La Gestión de Proyectos de Ingeniería Civil

## Introducción

La gestión de proyectos en la ingeniería civil es fundamental para materializar las soluciones de problemas o necesidades identificadas tanto a nivel público como privado en los distintos aspectos social, económio, político y ambiental, los cuales inciden en la calidad de vida de las personas, en la entrega de productos y servicios, así como también en el desarrollo de un territorio.

Historicamente y según la literatura, la gestión de proyectos de ingeniería utiliza herramientas y técnicas que se soportan en buenas prácticas y se dan de acuerdo a estandares internacionales, con el fin de que se pueda asegurar el logro  en cualquier tipo de proyecto, como edificaciones, puentes, vías, transporte, obras de protección de ríos y costas, hidroeléctricas, consultorías de diseño y planeación, etc.  Con la materialización de estos proyectos se asegura el logro de los objetivos estratégicos (producto o servicio) del proyecto en un tiempo determinado.


## Objetivos de aprendizaje

-   Definir un proyecto.

-   Definir el flujo de proceso de la gerencia de proyectos.

-   Diferenciar los criterios y factores de éxito de un proyecto.

## Definición de proyecto

En la literatura existente se pueden encontrar múltiples definiciones de lo qué es un proyecto. En este apartado se presentan algunas de las más conocidas y que considero pueden ser de fácil comprensión.

Según [@turnerrodneyHandbookProjectBased2008], *un proyecto es un esfuerzo en el que se organizan los recursos humanos, financieros y de materiales de una manera novedosa para emprender un ámbito de trabajo único, según especificaciones dadas, dentro de limitaciones de costo y tiempo, a fin de lograr un cambio beneficioso definido por objetivos cualitativos y cuantitativos*.

Por otra parte, [@bakkerhansManagementEngineeringProjects] presenta la definición dada por el Instituto de Gerencia de Proyectos (Project Management Institute - PMI) el cual define un proyecto como *un esfuerzo temporal que se realiza para crear un producto, servicio o resultado único*.

El organismo profesional más grande paura gerentes de proyectos del Reino Unido, la Asociación para la Gestión de Proyectos (Association for Project Management- APM), tiene la siguiente definición. *Los proyectos son esfuerzos únicos y transitorios emprendidos para lograr un resultado deseado*.

Proyectos en Entornos Controlados (término más comúnmente conocido como PRINCE2), define un proyecto como *una organización temporal que ha sido creada con el propósito de entregar uno o más productos comerciales de acuerdo con un caso comercial predefinido*.

Para este libro se tendrán en cuenta las definiciones de [@turnerrodneyHandbookProjectBased2008] y del PMI. Siendo estas una de las más utilizadas en América y que dan mayor claridad sobre el tema.

Teniendo en cuenta las definiciones anteriores se puede decir que las actividades y el esfuerzo de construir una vivienda, comprar un vehículo, realizar una tesis de posgrado, escribir un libro, construir un celular, desarrollar un software, entre otras se consideran un proyecto. Para que la gestión de los mismos facilite la entrega de los mismos en un tiempo y costo especifico se utilizan diferentes metodologías, las cuales se abordarán en este libro, el cual se enfocará más que todo en proyectos de ingeniería civil.

Para una mayor comprensión de los temas abordados, se recomienda tener en cuenta todos los términos asociados a la gestión de proyectos, incluyendo las abreviaturas y considerar que muchos términos tienen su origen en inglés.

## Definir el flujo de proceso de la gerencia de proyectos

La gerencia de proyectos tiene en cuenta el enfoque definido para la gestión de un proyecto específico. En este apartado se presenta el flujo de proceso de la gerencia de proyectos para un enfoque tradicional y uno ágil. 
El enfoque tradicional de acuerdo con el PMBOK se define como una serie de técnicas y herramientas que se puede ser aplicadas a una actividad que pretende entregar un producto final o un servicio.

En la ingeniería civil este enfoque ha sido utilizado por muchas decadas para los diferentes tipos de proyectos, como por ejemplo construcción de edificaciones, construcción de vías, construcción y/o mantenimiento de presas, entre otros. 
El enfoque tradicional se ha utilizado de la mano con una estructura de gobernanza vertical de arriba hacia abajo. Lo que indica que la dirección y la asignación de tareas son establecidas desde un nivel ejecutivo hasta llegar a la organización. De acuerdo con [@llarikantolaAdvancesHumanFactors2018] este estilo de liderazgo se basa en el mando, control y jerarquía. El enfoque en sí es orientado al plan desde el comienzo del proyecto y tiene poca flexibilidad para que sea modificado posteriormente. Este plan se realiza a su vez de forma centralizada dentro de la organización. Por lo que en un proyecto tradicional se asume que los eventos son predecibles y tanto las herramientas y técnicas a utilizar son claramente identificadas.

![Proceso de la gerencia de proyectos de proyectos tradicionales según el PMI. Fuente: [@llarikantolaAdvancesHumanFactors2018]](proceso.png){width="100%"}

El enfoque moderno de gestión de proyectos como Lean y la gestión de groyectos Ágil según [@llarikantolaAdvancesHumanFactors2018], es ampliamente utilizada por los desarrolladores de software y es fuertemente iterativa e incremental, aquí los involucrados y los desarrolladores trabajan de forma muy cercana para entender el área de interés, determinar los requerimientos y priorizar las funcionalidades. 

En el enfoque ágil se realizan muchas iteraciones planeadas de forma rápida y que se desarrollan en ciclos, lo que contribuye en la mejora continua del producto y facilita la posibilidad de realizar modificaciones de acuerdo con las solicitudes de cambio del usuario y de los involucrados durante el ciclo de vida del proyecto.

![Proceso del ciclo de vida de un proyecto ágil. Fuente: [@llarikantolaAdvancesHumanFactors2018]](procesoagil.png){width="100%"}
